---
- name: Setup Fedora Workstation
  hosts: "localhost"
  connection: local
  become: true
  gather_facts: true

  vars_files:
    - vars/vars.yml

  tasks:
    # - include_tasks: tasks/repos.yml
    # - include_tasks: tasks/packages.yml
    - include_tasks: tasks/docker.yml
    # - include_tasks: tasks/software.yml
    # - include_tasks: tasks/system.yml
    # - include_tasks: tasks/users.yml
    # - include_tasks: tasks/fonts.yml

  handlers:
    - name: reload systemd
      command: systemctl daemon-reload
