- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
  when: always_update_packages

- name: Install extra packages
  dnf:
    name:
      - bat
      - bottom
      - exa
      - fd-find # required for fzf.fish
      - fish
      - fuse-sshfs
      - fzf
      - git
      - gnome-extensions-app
      - gnome-tweak-tool
      - golang
      - htop
      - iotop
      - jq
      - mozilla-openh264
      - ripgrep
      - smartmontools
      - tmux
      - vim-enhanced
      - xl2tpd
      - youtube-dl
      - z
    state: installed

- name: Install starship
  ansible.builtin.import_role:
    name: andrewrothstein.starship
