- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
  when: always_update_packages

- name: Install extra packages
  dnf:
    name:
      - bat
      - bottom
      - exa
      - fd-find # required for fzf.fish
      - fish
      - fuse-sshfs
      - fzf
      - git
      - gnome-tweak-tool
      - golang
      - htop
      - iotop
      - jq
      - mozilla-openh264
      - NetworkManager-l2tp
      - NetworkManager-l2tp-gnome
      - ripgrep
      - smartmontools
      - tmux
      - vim-enhanced
      - xl2tpd
      - z
    state: installed

- name: Install extra fonts
  dnf:
    name: jetbrains-mono-fonts
    state: installed
  when: install_extra_fonts

- name: Install starship
  ansible.builtin.import_role:
    name: andrewrothstein.starship
