---
- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
  when: always_update_packages

- name: Set dnf max parallel downloads to 10
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: max_parallel_downloads=10

- name: Set dnf fastestmirror to true
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: fastestmirror=True

- name: Install extra packages
  dnf:
    name:
      - bat
      - bottom
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - eza
      - fd-find # required for fzf.fish
      - fish
      - fuse-sshfs
      - fzf
      - git
      - gnome-extensions-app
      - gnome-tweak-tool
      - golang
      - htop
      - iotop
      - jq
      - mozilla-openh264
      - ripgrep
      - smartmontools
      - tmux
      - vim-enhanced
      - xl2tpd
      - youtube-dl
      - z
    state: installed

- name: Windows boot entry exists
  command: grep "^menuentry.*Windows Boot Manager.*" /boot/grub2/grub.cfg
  register: windows_boot_entry
  changed_when: false
  ignore_errors: true

- name: Register refind installed
  stat:
    path: /boot/efi/EFI/refind
  register: refind_efi_directory

- name: Install refind
  dnf:
    name: rEFInd
    state: present
  when: windows_boot_entry.rc == 0 and not refind_efi_directory.stat.exists

- name: Execute refind install
  changed_when: false
  command: refind-install
  when: windows_boot_entry.rc == 0 and not refind_efi_directory.stat.exists

- name: Install starship
  ansible.builtin.import_role:
    name: andrewrothstein.starship

- name: Enable and start docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Create docker group
  group:
    name: "docker"
    state: present
