---
- name: Install VS Code
  dnf:
    name: code
    state: present
  when: install_vscode

- name: Install 1Password
  dnf:
    name: 1password
    state: present
  when: install_1password

- name: Install blackbox terminal
  become: false
  flatpak:
    name: com.raggesilver.BlackBox
    state: present
    method: user

- name: Install Docker
  dnf:
    name:
      [
        "docker-ce",
        "docker-ce-cli",
        "containerd.io",
        "docker-buildx-plugin",
        "docker-compose-plugin",
      ]
    state: present
