---
- name: Enable minimize/maximize buttons
  become: false
  changed_when: false
  command: gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"

- name: Remove logout delay
  become: false
  changed_when: false
  command: gsettings set org.gnome.SessionManager logout-prompt false

- name: Enable nightlight
  become: false
  changed_when: false
  command: gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
