---
- name: Save username
  become: false
  shell: whoami
  register: username
  changed_when: false

- block:
    - name: Change shell to fish
      user:
        name: "{{ username.stdout }}"
        shell: /usr/bin/fish

    - name: Copy fish.config
      copy:
        src: files/fish/config.fish
        dest: /home/{{ username.stdout }}/.config/fish/config.fish

    - name: Copy fish plugins file
      copy:
        src: files/fish/fish_plugins
        dest: /home/{{ username.stdout }}/.config/fish/fish_plugins

  when: use_fish_shell

- name: Create docker group
  group:
    name: "docker"
    state: present

- name: Add user to group
  user:
    name: "{{ username.stdout }}"
    groups: docker
    append: yes

- name: Copy smb credentials file
  ansible.builtin.copy:
    src: files/.smb
    dest: /home/{{ username.stdout }}/.smb
    owner: "{{ username.stdout }}"
    group: "{{ username.stdout }}"
    mode: "0600"

- name: Auto-mount document-inbox
  ansible.posix.mount:
    path: /home/{{ username.stdout }}/document-inbox
    src: //{{ document_host }}/document-inbox
    fstype: cifs
    opts: credentials=/home/{{ username.stdout }}/.smb,uid=1000,gid=1000,nofail,soft,x-systemd.device-timeout=10ms
    state: present
  notify:
    - reload systemd
